<div class="user-comments">
    <div class="ws-reply-box">
        <div class="ws-avatar">
            <img src="/img/avatar.png" alt="ikk">
        </div>
        <?= $this->tag->form(array('/thread/'.$thread->uniqueKey.'/comments/save','id'=>'ws_comment_form_0',
            'class'=>'ws_comment_comment_new_form','method'=>'post','data-parent')) ?>
            <textarea class="input" name="content" rows="4"></textarea>
            <input type="hidden" name="username" value="测试" />
            <div style="margin-top: 5px;">
    <!--            <input type="text" class="form-control captcha" name="captcha" value="" /> <img src="/thread/captcha"  class="img-rounded" />-->
            <input class="submit btn btn-primary" type="submit" value="回复"/>
            </div>
        </form>
    </div>
    <div class="ws-title">
        <span class="amount"><?=$thread->numComments ?></span>条评论
        <div class="ws-sort">
            <a class="ws-order-desc <?if($sorter=='-created_at') echo 'ws-current' ?>" data-sort="-created_at">最新</a>
            <a class="ws-order-asc <?if($sorter=='created_at') echo 'ws-current' ?>" data-sort="created_at">最早</a>
            <a class="ws-order-hot <?if($sorter=='hot') echo 'ws-current' ?>" data-sort="hot">最热</a>
        </div>
    </div>
    <div class="ws-comments" id="ws_comment_list">
        <?
        foreach($comments as $comment){
            $this->partial('thread/comment', array('comment' => $comment,'thread'=>$thread));
            $childrenComments = $comment->getChildrenComments();
            if(count($childrenComments)){
                foreach($childrenComments as $comment){
                    $this->partial('thread/comment', array('comment' => $comment,'thread'=>$thread));
                }
            }
        }
        ?>
    </div>
    <?if($pager->total_pages > 1):?>
        <div class="ws-paginator">

        <?if($pager->current > 2):?>
            <a data-page="<?=$pager->first?>" href="javascript:void(0);"><i class="fa fa-angle-double-left"></i></a>
        <?endif?>
        <?if($pager->current > 1):?>
            <a data-page="<?=$pager->before?>" href="javascript:void(0);"><i class="fa fa-angle-left"></i></a>
        <?endif?>
        <?if($pager->prev_skip):?>
            <span>...</span>
        <?endif?>
        <?if($pager->prev_range):?>
            <?foreach($pager->prev_range as $page):?>
                <a data-page="<?=$page?>" href="javascript:void(0);"><?=$page?></a>
            <?endforeach?>
        <?endif?>
            <span class="current"><?=$pager->current?></span>
        <?if($pager->next_range):?>
            <?foreach($pager->next_range as $page):?>
                <a data-page="<?=$page?>" href="javascript:void(0);"><?=$page?></a>
            <?endforeach?>
        <?endif?>
        <?if($pager->next_skip):?>
            <span>...</span>
        <?endif?>
        <?if($pager->next && $pager->current < $pager->last):?>
            <a data-page="<?=$pager->next?>" href="javascript:void(0);"><i class="fa fa-angle-right"></i></a>
        <?endif?>
        <?if($pager->current < $pager->last):?>
            <a data-page="<?=$pager->last?>" href="javascript:void(0);"><i class="fa fa-angle-double-right"></i></a>
        <?endif?>
    </div>
    <?endif?>
</div>
