<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/dashboard">Home</a>
        </li>

        <li>
            <a href="/admin/comment" class="active">Comment List</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">
<div class="page-header">
    <h1>
        Comment Thread
    </h1>
</div>
<!-- /.page-header -->

<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <form class="form-horizontal" role="form" action="" method="post">
            <!-- #section:elements.form -->
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Permalink</label>

                <div class="col-sm-9">
                    <?=$form->render('permalink', array( 'readonly'=>'true','class'=>'col-xs-10 col-sm-5'))?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1">Title</label>

                <div class="col-sm-9">
                    <?=$form->render('title', array( 'class'=>'col-xs-10 col-sm-5'))?>
                </div>
            </div>

            <!-- /section:elements.form -->
            <div class="space-4"></div>

            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right"> Default comment status</label>

                <div class="col-sm-9">
                    <?=$form->render('defaultCommentStatus', array('class'=>'ace'))?>
<!--                    <label>-->
<!--                        <input name="defaultCommentStatus" type="radio" class="ace">-->
<!--                        <span class="lbl">Approved</span>-->
<!--                    </label>-->
<!---->
<!--                    <label>-->
<!--                        <input name="defaultCommentStatus" type="radio" class="ace">-->
<!--                        <span class="lbl">Pending</span>-->
<!--                    </label>-->
                </div>
            </div>

            <div class="space-4"></div>

            <div class="clearfix form-actions">
                <div class="col-md-offset-3 col-md-9">
                    <button class="btn btn-info" type="submit">
                        <i class="ace-icon fa fa-check bigger-110"></i>
                        Submit
                    </button>

                    &nbsp; &nbsp; &nbsp;
                    <button class="btn" type="reset">
                        <i class="ace-icon fa fa-undo bigger-110"></i>
                        Reset
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>