<!DOCTYPE html>
<html>
<head>
	<title><?=$this->placeholder->block('title', '华尔街见闻移动版');?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<link href="favicon.ico" rel="shortcut icon" type="image/x-icon">
	<link rel="stylesheet" href="http://cdn.static.wallstreetcn.com/css/bootstrap.min.css" />
	<link rel="stylesheet" href="http://cdn.static.wallstreetcn.com/css/font-awesome.min.css" />
	<style type="text/css">
		.toolbar{
			position: relative;
			background-color: #0f496d;
			background-image: none;
			border: 0;
			margin: 0;
			padding: 0;
			height: 36px;
			min-height: 36px;
			font-size: 18px;
			font-weight: normal;
		}
		
		.toolbar .home{
			color:white;
			left:5px;
			font-size:22px;
			position:absolute;
		}
		
		.toolbar .home img{
			max-height: 80%;
		}
		
		.toolbar .app-download{
			right:5px;
			position:absolute;
			margin-top: 3px;
		}
		
		.toolbar .app-download img{
			max-height: 70%;
		}
		
		.toolbar .title {
			position: absolute;
			left: 0;
			right: 0;
			margin: 0 auto;
			font-size: 16px;
			color: #fff;
			width: 6.5em;
			text-align: left;
			line-height: 30px;
			height: 34px;
		}
		
		.news-list{
			
			position: absolute;
			width: 100%;
			/*height: 100%;*/
		}
		
		.news-font{
			margin:0px;
			font-weight:normal;
			font-family: verdana, 'Hiragino Sans GB', 'Microsoft YaHei', 'WenQuanYi Micro Hei', sans-serif;
		}
		
		.news-list .news {
			position: relative;
			width: 100%;
			min-height: 42px !important;
			border-top: 1px solid #dedede;
			padding: 12px 15px;
		}
		
		.news-list .news .cover {
			width: 75px;
			height: 60px;
			float: left;
			background: url('/wscnwap/cover.png') 0 0 no-repeat;
			background-size: 75px 60px;
			-o-background-size: 75px 60px;
			-webkit-background-size: 75px 60px;
		}
		
		.news-list .news .title {
			position: absolute;
			left: 75px;
			right: 0;
			overflow: hidden;
			line-height: 20px;
			height: 40px;
			padding-left: 30px;
			font-size:15px;
		}
		
		.news-list .news .time {
			position: absolute;
			font-size: 12px;
			right: 15px;
			bottom: 12px;
			color:#666666;
		}
		
		.news-more{
			position: absolute;
			left: 0;
			right: 0;
			bottom:0;
			margin: 0 auto;
			width: 8em;
			margin-bottom: 10px;
		}
		
		.news-more span{
			border: solid #0f496d 1px;
			font-size:12px;
			padding:5px 30px;
			color:#0f496d;
			border-radius: 5px;
			cursor:pointer;
		}
	
		.news-info{
			padding: 12px 15px !important;
			-webkit-transform: translate3d(0px, 0px, 0px);
			/*position: absolute;
			min-width: 100%;
			min-height: 100%;
			height: auto!important;
			width: auto!important;*/
			width:100%;
			height:100%;
			background: #f7f7f7;
			font-size: 16px;
		}
		
		.news-info .title {
			font-size: 20px;
		}
		
		.news-info .meta {
			position: relative;
			font-size: 12px;
			line-height: 24px;
			padding-bottom: 6px;
			color: #999;
			border-bottom: 1px solid #999;
			margin: 10px 0;
		}
		
		.news-info .content {
			line-height: 1.5;
			margin-bottom: 20px;
		}
		
		.news-info .content img {
			max-width: 100%!important;
			height: auto!important;
		}

        .news-info .meta>.item {
                margin-right: 1em;
        }	</style>
	
</head>
<body>

<div style="width: 100% !important; height: 100% !important;">
	<div class="toolbar">
		<a href="/"><div class="home"><img src="/wscnwap/logo.png"/></div></a>
		<a href="http://wallstreetcn.com/downloadapp.html" target="_blank"><div class="app-download"><img src="/wscnwap/app-download.png" /></div></a>
	</div>
<?=$this->getContent()?>
</div>

<script src="http://cdn.static.wallstreetcn.com/js/jquery-1.10.2.min.js"></script>
<script src="http://cdn.static.wallstreetcn.com/js/moment-with-langs.min.js"></script>

<script type="text/javascript">

function updateTimeLabel($list){
	$list.each(function(){
		var time = $(this);
        time.html(moment(time.attr("data-timestamp") * 1000).fromNow());
	});
}

$(document).ready(function(){
    moment.lang('zh-cn');
	
	updateTimeLabel($(".agotime"));
	
	//fix firefox,ie max-width bug
	if(/firefox/.test(navigator.userAgent.toLowerCase()) || !!window.ActiveXObject || "ActiveXObject" in window){
		$(".home img,.app-download img").css("max-width","50%");
	}
	
	$(".news-more").click(function(){
		var hash = document.location.hash,page;
		hash == "" ? (page = 1) : (page = 1 * hash.split("=")[1] + 1);
		document.location.hash = "page=" + page;
		
		$(".news-more span").html("正在加载");
		$.get("/?page=" + page,function(result){
			$(".news-more span").html("正在更多");
			var newsList = $(".news-list a",result);//.insertAfter(".news-list:last");
			updateTimeLabel(newsList.find(".agotime"));
			newsList.insertAfter(".news-list a:last");
		});
	});
});
</script>

<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-19303398-2']);
		_gaq.push(['_setDomainName', '.wallstreetcn.com']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>    
	<script>
		var _hmt = _hmt || [];
		(function() {
			var hm = document.createElement("script");
			hm.src = "//hm.baidu.com/hm.js?c9477ef9d8ebaa27c94f86cc3f505fa5";
			var s = document.getElementsByTagName("script")[0]; 
			s.parentNode.insertBefore(hm, s);
		})();
	</script>
</body>
</html>

